repository:
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
branches:
  - name: main
    protection:
      required_status_checks: null
      enforce_admins: true
      required_pull_request_reviews: null
      restrictions: null
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
